import Head from "next/head";
import styles from "@/styles/Home.module.css";
import NavBar from "@/components/NavBar";
import Hero from "@/components/hero";
import Projects from "@/components/projects";
import Experience from "@/components/experience";
import FooterContact from "@/components/footerContact";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <NavBar
          heroId="#hero"
          projectsId="#projects"
          experienceId="#experience"
          reachOutId="#reachOut"
        />
        <Hero id="hero" />
        <Projects id="projects" />
        <Experience id="experience" />
        <FooterContact id="reachOut" />
      </main>
    </>
  );
}
