const experience = [
  {
    id: 1,
    title: "Full Stack Developer",
    company: "Edgemony",
    location: "Palermo, Sicily, Italy",
    start: "October 2023",
    end: "April 2024",
    duration: "7 months",
    responsibilities: [
      "Led the development team to create 'Just Play', a web application tailored for sports enthusiasts.",
      "Used Next.js, React.js, MongoDB, and Sass to architect and build a user-friendly platform for organizing real-world sports matches.",
      "Implemented integrated authentication features to enable personalized user profiles and seamless friend management.",
      "Designed and integrated a comprehensive rating system to evaluate Fair Play, Skill, and Punctuality after each match.",
    ],
    techUsed: [
      "Next.js",
      "React.js",
      "Sass",
      "MongoDB",
      "Mongoose",
      "JavaScript",
    ],
    projectLink: "https://justplay-app-cb8.vercel.app/",
    repositoryLink: "https://github.com/kirkgio92/JustPlay-cb8-gruppo-c",
  },
  {
    id: 2,
    title: "Senior Finance Analyst",
    company: "Amazon",
    location: "Bratislava, Slovakia",
    start: "December 2021",
    end: "May 2023",
    duration: "1 year 6 months",
    responsibilities: [
      "Supported a team of 30 people across various marketplaces.",
      "Created SQL reports for upper management.",
      "Managed high-risk escalations and improved data accuracy in automated reports.",
      "Drafted and prepared Standard Operating Procedure guidelines.",
      "Authorized payments after analysis and approval from the team.",
    ],
    techUsed: ["SQL", "Data Analytics", "Microsoft Word"],
  },
  {
    id: 3,
    title: "Finance Analyst",
    company: "Amazon",
    location: "Bratislava, Slovakia",
    start: "November 2020",
    end: "November 2021",
    duration: "1 year 1 month",
    responsibilities: [
      "Handled invoice disputes related to product shortages.",
      "Collaborated with internal departments and Account Managers to resolve disputes.",
      "Developed an SQL-based semi-automated process to handle data and improve efficiency.",
      "Managed escalations and bulk cases for priority vendors.",
      "Worked on process improvements to boost team productivity.",
    ],
    techUsed: ["SQL", "Data Analytics", "Microsoft Excel"],
  },
  {
    id: 4,
    title: "Catalog Quality Associate",
    company: "Amazon",
    location: "Bratislava, Slovakia",
    start: "August 2019",
    end: "October 2020",
    duration: "1 year 3 months",
    responsibilities: [
      "Performed quality checks on Amazon catalog data for Machine Learning models.",
      "Translated and localized validated data entries for various marketplaces.",
      "Trained 12 people across different market locations and mentored new hires.",
      "Acted as a language specialist and Super Verifier for non-native speakers.",
    ],
    techUsed: ["Machine Learning", "Data Management", "Localization"],
  },
  {
    id: 5,
    title: "Ops Support Specialist",
    company: "Amazon",
    location: "Bratislava, Slovakia",
    start: "February 2019",
    end: "July 2019",
    duration: "6 months",
    responsibilities: [
      "Identified and resolved defects in FBA Orders for Amazon.co.uk and Amazon.it.",
      "Provided support for high-severity tickets and escalations.",
      "Handled outbound communication with sellers on behalf of multiple departments.",
    ],
    techUsed: ["Trouble Ticketing System", "Defect Management"],
  },
  {
    id: 6,
    title: "Vendor Contact Management",
    company: "Amazon",
    location: "Bratislava, Slovakia",
    start: "February 2018",
    end: "January 2019",
    duration: "1 year",
    responsibilities: [
      "Provided daily support to vendors regarding catalog, chargebacks, and analytics.",
      "Resolved transportation issues and managed disputes.",
      "Supported new hires and collaborated across departments.",
      "Specialized in vendor platform operations and data analysis.",
    ],
    techUsed: ["Vendor Central Platform", "Data Analysis", "Excel"],
  },
  {
    id: 7,
    title: "Caterer for Restaurant and Bar",
    company: "Vindigni S.r.l.",
    location: "Scicli, Sicily, Italy",
    start: "July 2016",
    end: "August 2016",
    duration: "2 months",
    responsibilities: [
      "Provided supplies for two bars and two restaurants.",
      "Managed warehouse restocking and ensured quick fulfillment of needs.",
      "Worked on prioritization, multitasking, and customer orientation.",
    ],
  },
  {
    id: 8,
    title: "Engineering Office Collaborator",
    company: "Private Engineering Office",
    location: "Scicli, Sicily, Italy",
    start: "2011",
    end: "May 2016",
    duration: "5 years 5 months",
    responsibilities: [
      "Designed environments using AutoCAD.",
      "Handled customer requests, documentation, and invoice management.",
      "Conducted surveys for flats and grounds.",
    ],
    techUsed: ["AutoCAD", "Excel", "Surveying"],
  },
  {
    id: 9,
    title: "Architect Office Collaborator",
    company: "Private Architect Office",
    location: "Scicli, Sicily, Italy",
    start: "January 2014",
    end: "December 2014",
    duration: "1 year",
    responsibilities: [
      "Designed houses based on customer requests.",
      "Managed customer data and documentation.",
    ],
    techUsed: ["Design Software", "Data Management"],
  },
  {
    id: 10,
    title: "Bar Back",
    company: "Pata Pata Beach",
    location: "Scicli, Sicily, Italy",
    start: "July 2014",
    end: "August 2014",
    duration: "2 months",
    responsibilities: [
      "Assisted the bar with cocktail preparation and refilling bar stations.",
      "Prepared food for bar purposes and restocked fridges.",
      "Worked on customer care and teamwork.",
    ],
  },
  {
    id: 11,
    title: "Electrical Line Installer, Repairer",
    company: "SAIE - S.R.L.",
    location: "Scicli, Sicily, Italy",
    start: "October 2012",
    end: "November 2012",
    duration: "2 months",
    responsibilities: [
      "Installed and repaired electrical systems.",
      "Collaborated with team members to split tasks and ensure timely completion.",
    ],
  },
];

export default experience;
